=== PaulCrossan/self-service/schema/issueops-self-service-v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "issueops-self-service-schema-v1",
  "title": "GitHub IssueOps Self Service Action Schema",
  "description": "Schema for the GitHub IssueOps Self Service Actions",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "approvers": {
        "type": "array",
        "description": "List of Approving Users or GitHub Teams",
        "items": {
          "type": "string"
        }
      },
      "assignees": {
        "type": "array",
        "description": "List of Assigning Users",
        "items": {
          "type": "string",
          "pattern": "^[^/]*$"
        }
      },
      "category": {
        "type": "string",
        "description": "Category of the IssueOps Action",
        "enum": ["enterprise", "organization", "repository"]
      },
      "description": {
        "type": "string",
        "description": "Description of the IssueOps Action"
      },
      "icon": {
        "type": "string",
        "description": "Icon of the IssueOps Action"
      },
      "issueFormTemplate": {
        "type": "string",
        "description": "Issue Form Template of the IssueOps Action",
        "pattern": "^[^/]*$"
      },
      "issueTitle": {
        "type": "string",
        "description": "Issue Title of the IssueOps Action"
      },
      "label": {
        "type": "string",
        "description": "Label of the IssueOps Action"
      },
      "name": {
        "type": "string",
        "description": "Name of the IssueOps Action"
      }
    },
    "required": [
      "approvers",
      "assignees",
      "category",
      "description",
      "icon",
      "issueFormTemplate",
      "issueTitle",
      "label",
      "name"
    ]
  }
}

=== PaulCrossan/self-service/data/issue-ops.json
[
  {
    "approvers": [],
    "assignees": [],
    "category": "organization",
    "description": "Create an organization announcement banner.",
    "icon": "Volume2",
    "issueFormTemplate": "create-announcement.yml",
    "issueTitle": "[IssueOps] Create a new announcement",
    "label": "create-announcement",
    "name": "Announcement"
  },
  {
    "approvers": [],
    "assignees": [],
    "category": "organization",
    "description": "Create a project for your organization users and repositories.",
    "icon": "SquareKanban",
    "issueFormTemplate": "create-project.yml",
    "issueTitle": "[IssueOps] Create a new project",
    "label": "create-project",
    "name": "Project"
  },
  {
    "approvers": [],
    "assignees": [],
    "category": "organization",
    "description": "Create an organization variable to use in your GitHub Actions workflows.",
    "icon": "Variable",
    "issueFormTemplate": "create-actions-variable.yml",
    "issueTitle": "[IssueOps] Create a new GitHub Actions variable",
    "label": "create-actions-variable",
    "name": "GitHub Actions Variable"
  },
  {
    "approvers": ["@issue-ops/maintainers"],
    "assignees": [],
    "category": "organization",
    "description": "Transfer a repository. Requires enterprise admin approval.",
    "icon": "FolderSync",
    "issueFormTemplate": "create-repository-transfer.yml",
    "issueTitle": "[IssueOps] Create a new repository transfer",
    "label": "create-repository-transfer",
    "name": "Repository Transfer"
  },
  {
    "approvers": ["@issue-ops/maintainers"],
    "assignees": [],
    "category": "repository",
    "description": "Create a new repository in your organization.",
    "icon": "BookDashed",
    "issueFormTemplate": "create-repository.yml",
    "issueTitle": "[IssueOps] Create a new repository",
    "label": "create-repository",
    "name": "Create Repository"
  },
  {
    "approvers": [],
    "assignees": [],
    "category": "repository",
    "description": "Rename a repository in your organization.",
    "icon": "BookMarked",
    "issueFormTemplate": "rename-repository.yml",
    "issueTitle": "[IssueOps] Rename a repository",
    "label": "rename-repository",
    "name": "Rename Repository"
  },
  {
    "approvers": [],
    "assignees": [],
    "category": "repository",
    "description": "Archive a repository in your organization, converting it to read-only.",
    "icon": "BookLock",
    "issueFormTemplate": "archive-repository.yml",
    "issueTitle": "[IssueOps] Archive a repository",
    "label": "archive-repository",
    "name": "Archive Repository"
  },
  {
    "approvers": ["@issue-ops/maintainers"],
    "assignees": [],
    "category": "repository",
    "description": "Change the visibility of your repository.",
    "icon": "BookUp2",
    "issueFormTemplate": "change-repository-visibility.yml",
    "issueTitle": "[IssueOps] Change the visibility of a repository",
    "label": "change-repository-visibility",
    "name": "Change Visibility"
  },
  {
    "approvers": [],
    "assignees": [],
    "category": "repository",
    "description": "Unarchive a repository.",
    "icon": "BookUp2",
    "issueFormTemplate": "unarchive-repository.yml",
    "issueTitle": "[IssueOps] Unarchive a repository",
    "label": "unarchive-repository",
    "name": "Unarchive Repository"
  }
]
